-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 23:27:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema booksgame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema booksgame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booksgame` DEFAULT CHARACTER SET utf8 ;
USE `booksgame` ;

-- -----------------------------------------------------
-- Table `booksgame`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`utilisateur` (
  `idutilisateur` INT NOT NULL,
  `nom_util` VARCHAR(45) NULL,
  `equipe_idequipe` INT NOT NULL,
  `recompense_idrecompense` INT NOT NULL,
  `compte` INT NULL,
  PRIMARY KEY (`idutilisateur`, `equipe_idequipe`, `recompense_idrecompense`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`liste_livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`liste_livre` (
  `idliste_livre` INT NOT NULL,
  PRIMARY KEY (`idliste_livre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`theme` (
  `id_theme` INT NOT NULL,
  `titre_theme` VARCHAR(45) NULL,
  `nom_salle` VARCHAR(45) NULL,
  PRIMARY KEY (`id_theme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`livre` (
  `idlivre` INT NOT NULL,
  `titre_livre` VARCHAR(45) NULL,
  `edition` VARCHAR(45) NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  `liste_livre_idliste_livre` INT NOT NULL,
  `theme_id_theme` INT NOT NULL,
  PRIMARY KEY (`idlivre`, `utilisateur_idutilisateur`, `liste_livre_idliste_livre`, `theme_id_theme`),
  INDEX `fk_livre_liste_livre1_idx` (`liste_livre_idliste_livre` ASC),
  INDEX `fk_livre_theme1_idx` (`theme_id_theme` ASC),
  CONSTRAINT `fk_livre_liste_livre1`
    FOREIGN KEY (`liste_livre_idliste_livre`)
    REFERENCES `booksgame`.`liste_livre` (`idliste_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_theme1`
    FOREIGN KEY (`theme_id_theme`)
    REFERENCES `booksgame`.`theme` (`id_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`prof` (
  `idprof` INT NOT NULL,
  `nom_prof` VARCHAR(45) NULL,
  `profcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idprof`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`point` (
  `idpoint` INT NOT NULL,
  `nombre_point` VARCHAR(45) NULL,
  PRIMARY KEY (`idpoint`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`recompense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`recompense` (
  `idrecompense` INT NOT NULL,
  `type_recompense` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecompense`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`equipe` (
  `idequipe` INT NOT NULL,
  `couleur_equipe` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`quiz` (
  `idquiz` INT NOT NULL,
  `contenue_quizz` VARCHAR(45) NULL,
  PRIMARY KEY (`idquiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`reponse` (
  `idreponse` INT NOT NULL,
  `contenue_reponse` VARCHAR(45) NULL,
  PRIMARY KEY (`idreponse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`question` (
  `idquestion` INT NOT NULL,
  `quiz_idquiz` INT NOT NULL,
  `reponse_idreponse` INT NOT NULL,
  `cotenue_question` VARCHAR(45) NULL,
  PRIMARY KEY (`idquestion`, `quiz_idquiz`, `reponse_idreponse`),
  INDEX `fk_question_quiz1_idx` (`quiz_idquiz` ASC),
  INDEX `fk_question_reponse1_idx` (`reponse_idreponse` ASC),
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz_idquiz`)
    REFERENCES `booksgame`.`quiz` (`idquiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_reponse1`
    FOREIGN KEY (`reponse_idreponse`)
    REFERENCES `booksgame`.`reponse` (`idreponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`point_has_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`point_has_utilisateur` (
  `point_idpoint` INT NOT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  PRIMARY KEY (`point_idpoint`, `utilisateur_idutilisateur`),
  INDEX `fk_point_has_utilisateur_utilisateur1_idx` (`utilisateur_idutilisateur` ASC),
  INDEX `fk_point_has_utilisateur_point_idx` (`point_idpoint` ASC),
  CONSTRAINT `fk_point_has_utilisateur_point`
    FOREIGN KEY (`point_idpoint`)
    REFERENCES `booksgame`.`point` (`idpoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_point_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur`)
    REFERENCES `booksgame`.`utilisateur` (`idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`livre_has_prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`livre_has_prof` (
  `livre_idlivre` INT NOT NULL,
  `livre_utilisateur_idutilisateur` INT NOT NULL,
  `prof_idprof` INT NOT NULL,
  PRIMARY KEY (`livre_idlivre`, `livre_utilisateur_idutilisateur`, `prof_idprof`),
  INDEX `fk_livre_has_prof_prof1_idx` (`prof_idprof` ASC),
  INDEX `fk_livre_has_prof_livre1_idx` (`livre_idlivre` ASC, `livre_utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_livre_has_prof_livre1`
    FOREIGN KEY (`livre_idlivre` , `livre_utilisateur_idutilisateur`)
    REFERENCES `booksgame`.`livre` (`idlivre` , `utilisateur_idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_prof_prof1`
    FOREIGN KEY (`prof_idprof`)
    REFERENCES `booksgame`.`prof` (`idprof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`utilisateur_has_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`utilisateur_has_quiz` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `utilisateur_equipe_idequipe` INT NOT NULL,
  `quiz_idquiz` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `utilisateur_equipe_idequipe`, `quiz_idquiz`),
  INDEX `fk_utilisateur_has_quiz_quiz1_idx` (`quiz_idquiz` ASC),
  INDEX `fk_utilisateur_has_quiz_utilisateur1_idx` (`utilisateur_idutilisateur` ASC, `utilisateur_equipe_idequipe` ASC),
  CONSTRAINT `fk_utilisateur_has_quiz_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur` , `utilisateur_equipe_idequipe`)
    REFERENCES `booksgame`.`utilisateur` (`idutilisateur` , `equipe_idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_quiz_quiz1`
    FOREIGN KEY (`quiz_idquiz`)
    REFERENCES `booksgame`.`quiz` (`idquiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`livre_has_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`livre_has_utilisateur` (
  `livre_idlivre` INT NOT NULL,
  `livre_utilisateur_idutilisateur` INT NOT NULL,
  `utilisateur_idutilisateur` INT NOT NULL,
  `utilisateur_equipe_idequipe` INT NOT NULL,
  `utilisateur_recompense_idrecompense` INT NOT NULL,
  PRIMARY KEY (`livre_idlivre`, `livre_utilisateur_idutilisateur`, `utilisateur_idutilisateur`, `utilisateur_equipe_idequipe`, `utilisateur_recompense_idrecompense`),
  INDEX `fk_livre_has_utilisateur_utilisateur1_idx` (`utilisateur_idutilisateur` ASC, `utilisateur_equipe_idequipe` ASC, `utilisateur_recompense_idrecompense` ASC),
  INDEX `fk_livre_has_utilisateur_livre1_idx` (`livre_idlivre` ASC, `livre_utilisateur_idutilisateur` ASC),
  CONSTRAINT `fk_livre_has_utilisateur_livre1`
    FOREIGN KEY (`livre_idlivre` , `livre_utilisateur_idutilisateur`)
    REFERENCES `booksgame`.`livre` (`idlivre` , `utilisateur_idutilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur` , `utilisateur_equipe_idequipe` , `utilisateur_recompense_idrecompense`)
    REFERENCES `booksgame`.`utilisateur` (`idutilisateur` , `equipe_idequipe` , `recompense_idrecompense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`utilisateur_has_recompense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`utilisateur_has_recompense` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `utilisateur_equipe_idequipe` INT NOT NULL,
  `utilisateur_recompense_idrecompense` INT NOT NULL,
  `recompense_idrecompense` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `utilisateur_equipe_idequipe`, `utilisateur_recompense_idrecompense`, `recompense_idrecompense`),
  INDEX `fk_utilisateur_has_recompense_recompense1_idx` (`recompense_idrecompense` ASC),
  INDEX `fk_utilisateur_has_recompense_utilisateur1_idx` (`utilisateur_idutilisateur` ASC, `utilisateur_equipe_idequipe` ASC, `utilisateur_recompense_idrecompense` ASC),
  CONSTRAINT `fk_utilisateur_has_recompense_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur` , `utilisateur_equipe_idequipe` , `utilisateur_recompense_idrecompense`)
    REFERENCES `booksgame`.`utilisateur` (`idutilisateur` , `equipe_idequipe` , `recompense_idrecompense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_recompense_recompense1`
    FOREIGN KEY (`recompense_idrecompense`)
    REFERENCES `booksgame`.`recompense` (`idrecompense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksgame`.`utilisateur_has_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booksgame`.`utilisateur_has_equipe` (
  `utilisateur_idutilisateur` INT NOT NULL,
  `utilisateur_equipe_idequipe` INT NOT NULL,
  `utilisateur_recompense_idrecompense` INT NOT NULL,
  `equipe_idequipe` INT NOT NULL,
  PRIMARY KEY (`utilisateur_idutilisateur`, `utilisateur_equipe_idequipe`, `utilisateur_recompense_idrecompense`, `equipe_idequipe`),
  INDEX `fk_utilisateur_has_equipe_equipe1_idx` (`equipe_idequipe` ASC),
  INDEX `fk_utilisateur_has_equipe_utilisateur1_idx` (`utilisateur_idutilisateur` ASC, `utilisateur_equipe_idequipe` ASC, `utilisateur_recompense_idrecompense` ASC),
  CONSTRAINT `fk_utilisateur_has_equipe_utilisateur1`
    FOREIGN KEY (`utilisateur_idutilisateur` , `utilisateur_equipe_idequipe` , `utilisateur_recompense_idrecompense`)
    REFERENCES `booksgame`.`utilisateur` (`idutilisateur` , `equipe_idequipe` , `recompense_idrecompense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_equipe_equipe1`
    FOREIGN KEY (`equipe_idequipe`)
    REFERENCES `booksgame`.`equipe` (`idequipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
